### ISSUE TITLE
Receiving error in pipeline

### ISSUE THREAD

**Issue by Rum980** [LucasFidon/trustworthy-ai-fetal-brain-segmentation#6]
Hello,

Thank you for creating and sharing this software. I tried running the pipeline but am receiving an error after some time. Here's the traceback:

Traceback (most recent call last):
  File "run_segment.py", line 183, in <module>
    main(args)
  File "run_segment.py", line 102, in main
    softmax = load_softmax(pred_softmax_path, volume_info_path)
  File "/workspace/trustworthy-ai-fetal-brain-segmentation/src/deep_learning/inference_nnunet.py", line 34, in load_softmax
    softmax_cropped = np.load(softmax_path)['softmax'][None][0,...]
  File "/opt/conda/lib/python3.8/site-packages/numpy/lib/npyio.py", line 417, in load
    fid = stack.enter_context(open(os_fspath(file), "rb"))
**FileNotFoundError: [Errno 2] No such file or directory: '/data/M003/backboneAI/.npz'**

Note: M003 is the subject directory. In the backboneAI folder, there are three files listed:
- M004.nii.gz
- M004.npz
- M004.pkl

 The error seems as though it's not able to find .npz. Would you know how this can be resolved?

Thanks,
Ramana

**Comment by Rum980** [comment]
Okay, I figured this out. I put a forward slash ( / ) at the end of the output_folder. Once I removed this extra slash, it worked. 

Keeping this here in case anyone else makes the same mistake
